from typing import Callable, Protocol, runtime_checkable


@runtime_checkable
class MessageQueue(Protocol):
    def publish(self, msg: dict) -> None: ...
    def subscribe(self, handler: Callable[[dict], None]) -> None: ...
    def ack(self, msg_id: str) -> None: ...
    def nack(self, msg_id: str) -> None: ...
